[package]
name = "primitives"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
alloy-primitives.workspace = true

[lints]
workspace = true
