[package]
name = "montana"
description = "Montana Block Executor"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# common crates
sequencer.workspace = true

# execution crates
blocksource.workspace = true
database.workspace = true
runner.workspace = true

# alloy
alloy.workspace = true
op-alloy.workspace = true

# consensus crates
montana-batch-context.workspace = true
montana-batcher.workspace = true
montana-brotli.workspace = true
montana-derivation-runner.workspace = true
montana-pipeline.workspace = true

# utilities
montana-cli.workspace = true
montana-tui.workspace = true

# async
async-trait.workspace = true
tokio.workspace = true

# misc
clap.workspace = true
crossterm = { workspace = true, features = ["event-stream"] }
derive_more.workspace = true
eyre.workspace = true
ratatui.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
