[package]
name = "montana"
description = "Montana Block Executor"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# common crates
sequencer.workspace = true

# execution crates
runner.workspace = true

# consensus crates
montana-batcher.workspace = true
montana-brotli.workspace = true
montana-pipeline.workspace = true

# utilities
montana-cli.workspace = true

# async
async-trait.workspace = true
tokio.workspace = true

# misc
clap.workspace = true
eyre.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
