[package]
name = "montana"
description = "Montana Batch Submitter Execution Extension"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# internal
montana-cli.workspace = true

# misc
clap = { workspace = true, features = ["derive"] }
tracing.workspace = true
